version: "3.9"

services:
  main:
    image: ghcr.io/kareadita/kavita:0.8.4    # Using the stable branch from ghcr.io
    volumes:
      - /mnt/user/library/manga:/manga
      - /mnt/user/library/comics:/comics
      - /mnt/user/library/books:/books
      - /mnt/user/docker/volumes/kavita/config:/kavita/config     # /kavita/config must not be changed
    environment:
      - TZ=America/Chicago
    ports:
      - "5001:5000"
    networks:
      - reverse-proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.kavita.rule=Host(`testing.actuary.dev`)"
        - "traefik.http.routers.kavita.entrypoints=websecure"
        - "traefik.http.routers.kavita.service=kavita"
        - "traefik.http.routers.kavita.tls.certresolver=myresolver"
        - "traefik.http.services.kavita.loadbalancer.server.port=5000"
        ## Middlewares
        - "traefik.http.routers.kavita.middlewares=authentik"
        #DIUN
        - diun.enable = true
        - diun.notify_on = new
networks:
  reverse-proxy:
    external: true
